# Generated by Django 4.2.7 on 2026-03-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_attendance_created_at_leave_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('SL', 'Sick Leave'), ('PL', 'Paid Leave'), ('CL', 'Casual Leave'), ('AB', 'Absent')], max_length=2),
        ),
    ]
