# Generated by Django 4.2.7 on 2026-03-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_leave_approved_at_leave_approved_by_leave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='status',
        ),
    ]
