# Generated by Django 4.2.7 on 2026-03-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_leave_approved_at_remove_leave_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
